export const EventType = {
    /**敌人碰撞事件 */
    // BEGIN_CONTACT_ENEMY: "BEGIN_CONTACT_ENEMY",
    /**英雄碰撞 */
    // BEGIN_CONTACT_HERO: "BEGIN_CONTACT_HERO"

    HERO_GUN_FIRE: "HERO_GUN_FIRE",
    UPDATE_HP: "UPDATA_HP",
    UPDATE_KILLS_COUNT: "UPDATE_KILLS_COUNT",
    UPDATE_BATTLE_TIME: "UPDATE_BATTLE_TIME",
    BATTLE_END: "BATTLE_END",
    REFRESH_ENEMY: "REFRESH_ENEMY"
}